MODEL_EXECUTABLE_DIRECTORY = "assets"
MODEL_EXECUTABLE_PERMISSIONS = 0o777

AWS_ACCESS_KEY_ID_ENV = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV = "AWS_SECRET_ACCESS_KEY"

STATUS_DIAGNOSIS_FILE = "status.modelops"

DEFAULT_SHELL_COMMAND_TIMEOUT = 10.0

FILE_SIZE_LIMIT_FOR_HASHING_BYTES = 10240
