MODEL_EXECUTABLE_DIRECTORY = "assets"
MODEL_EXECUTABLE_PERMISSIONS = 0o777

AWS_ACCESS_KEY_ID_ENV = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV = "AWS_SECRET_ACCESS_KEY"


VERSION_PREFIX = "versoes"
INPUTS_PREFIX = "ingest"
INPUTS_ECHO_PREFIX = "entradas"
OUTPUTS_PREFIX = "saidas"


EXECUTION_ID_FILE = "id.modelops"
STATUS_DIAGNOSIS_FILE = "status.modelops"
SYNTHESIS_DIR = "sintese"


DEFAULT_SHELL_COMMAND_TIMEOUT = 10.0

FILE_SIZE_LIMIT_FOR_HASHING_BYTES = 5242880  # 5 MB
